### ISSUE TITLE
Precise the changeset for a freestyle project

### ISSUE THREAD

**Issue by Gwanhir** [jenkinsci/plasticscm-plugin#15]
Hello,

Is there a way to choose the changeset to update to on a freestyle project ?
The way our branches are setup now imply a lot of different branching and to avoid more complex branching + cherry pick when searching for a bug, it would be great if we can choose the changeset we want to build from. If no changeset specify, the last one for the chosen branch should be used.

Thanks.

**Comment by mig42** [comment]
Hi! Do you need to use build parameters or you just want to know how to configure a specific changeset in the selector?

**Comment by Gwanhir** [comment]
Hi! I wanted to use a specific changeset in the selector, as Carlos replied in [this](https://forum.plasticscm.com/topic/21180-external-tool-for-jenkins-automation/) post. But I didn't know was possible as I don't found any documentation on the selector.

**Comment by mig42** [comment]
I'm happy to know that you already found the answer 😃 There is indeed little documentation on the selector because it's a remnant of the previous Plastic SCM versions which isn't used anymore. We're planning on removing it in future versions of the Jenkins plugin and use a more straightforward syntax.
