### ISSUE TITLE
Subdirectory doesn't work with environment variables

### ISSUE THREAD

**Issue by Zetym** [jenkinsci/plasticscm-plugin#29]
As the title says. Previously (pre 3.x) I could use ${JOB_NAME} as workspace name to ensure I got workspace names that were unique enough to avoid collisions. Now with 3.x I get a workspace that is literally named ${JOB_NAME}.

**Comment by knapsu** [comment]
Workspace names are automatically generated since `3.0` release and will never collide with each other (always unique). Be aware that "workspace name" is not the same as "directory name". Previously those two were hard referenced and created confusion. Now you no longer need to worry about workspace names. Only think about to which directory you want the workspace to be placed in.

I believe what you are asking for is to have an improvement and allow environment variable substitution for the directory field.
